// default package
// Generated 23 nov 2023 17:45:51 by Hibernate Tools 5.2.13.Final
package Model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Authors generated by hbm2java
 */
@Entity
@Table(name = "Authors", catalog = "Library")
public class Authors implements java.io.Serializable {

	private Integer authorId;
	private String name;
	private String nationality;
	private Set<Books> bookses = new HashSet<Books>(0);
	private Set<AuthorDetails> authorDetailses = new HashSet<AuthorDetails>(0);

	public Authors() {
	}

	public Authors(String name, String nationality, Set<Books> bookses, Set<AuthorDetails> authorDetailses) {
		this.name = name;
		this.nationality = nationality;
		this.bookses = bookses;
		this.authorDetailses = authorDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AuthorID", unique = true, nullable = false)
	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	@Column(name = "Name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Nationality", length = 50)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authors")
	public Set<Books> getBookses() {
		return this.bookses;
	}

	public void setBookses(Set<Books> bookses) {
		this.bookses = bookses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authors")
	public Set<AuthorDetails> getAuthorDetailses() {
		return this.authorDetailses;
	}

	public void setAuthorDetailses(Set<AuthorDetails> authorDetailses) {
		this.authorDetailses = authorDetailses;
	}

}
