package Model;

// default package
// Generated 23 nov 2023 17:45:51 by Hibernate Tools 5.2.13.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AuthorDetails generated by hbm2java
 */
@Entity
@Table(name = "AuthorDetails", catalog = "Library")
public class AuthorDetails implements java.io.Serializable {

	private int authorDetailsId;
	private Authors authors;
	private String wikipedia;
	private String awards;

	public AuthorDetails() {
	}

	public AuthorDetails(int authorDetailsId, Authors authors) {
		this.authorDetailsId = authorDetailsId;
		this.authors = authors;
	}

	public AuthorDetails(int authorDetailsId, Authors authors, String wikipedia, String awards) {
		this.authorDetailsId = authorDetailsId;
		this.authors = authors;
		this.wikipedia = wikipedia;
		this.awards = awards;
	}

	@Id

	@Column(name = "AuthorDetailsID", unique = true, nullable = false)
	public int getAuthorDetailsId() {
		return this.authorDetailsId;
	}

	public void setAuthorDetailsId(int authorDetailsId) {
		this.authorDetailsId = authorDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author_id", nullable = false)
	public Authors getAuthors() {
		return this.authors;
	}

	public void setAuthors(Authors authors) {
		this.authors = authors;
	}

	@Column(name = "wikipedia")
	public String getWikipedia() {
		return this.wikipedia;
	}

	public void setWikipedia(String wikipedia) {
		this.wikipedia = wikipedia;
	}

	@Column(name = "awards")
	public String getAwards() {
		return this.awards;
	}

	public void setAwards(String awards) {
		this.awards = awards;
	}

}
