package Model;

// Generated 23 nov 2023 17:45:51 by Hibernate Tools 5.2.13.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Books generated by hbm2java
 */
@Entity
@Table(name = "Books", catalog = "Library")
public class Books implements java.io.Serializable {

	private Integer bookId;
	private Authors authors;
	private String title;
	private Integer publicationYear;
	private Set<Categories> categorieses = new HashSet<Categories>(0);

	public Books() {
	}

	public Books(Authors authors, String title, Integer publicationYear, Set<Categories> categorieses) {
		this.authors = authors;
		this.title = title;
		this.publicationYear = publicationYear;
		this.categorieses = categorieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BookID", unique = true, nullable = false)
	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AuthorID")
	public Authors getAuthors() {
		return this.authors;
	}

	public void setAuthors(Authors authors) {
		this.authors = authors;
	}

	@Column(name = "Title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "PublicationYear")
	public Integer getPublicationYear() {
		return this.publicationYear;
	}

	public void setPublicationYear(Integer publicationYear) {
		this.publicationYear = publicationYear;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Books_Categories", catalog = "Library", joinColumns = {
			@JoinColumn(name = "BookID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "CategoryID", nullable = false, updatable = false) })
	public Set<Categories> getCategorieses() {
		return this.categorieses;
	}

	public void setCategorieses(Set<Categories> categorieses) {
		this.categorieses = categorieses;
	}

}
